name: Deploy to heroku

on:
    push:
        branches:
            - deploy

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.8.8
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                  heroku_email: ${{secrets.HEROKU_EMAIL}}
              env:
                  HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
                  HD_CLIENT_ID: ${{secrets.CLIENT_ID}}
                  HD_GUILD_ID: ${{secrets.GUILD_ID}}
